// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjekatPUSGS.Data;

namespace ProjekatPUSGS.Migrations
{
    [DbContext(typeof(ProjekatContext))]
    [Migration("20200515210608_migracija2")]
    partial class migracija2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProjekatPUSGS.Models.Aviokompanija", b =>
                {
                    b.Property<int>("IdAvio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenovnikIInfoOPrtljagu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destinacije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KonfSegmenataIMesta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Letovi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotivniOpis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpisakKarataSaPopustom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdAvio");

                    b.ToTable("Kompanije");
                });

            modelBuilder.Entity("ProjekatPUSGS.Models.Korisnik", b =>
                {
                    b.Property<int>("IdKorisnik")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojTelefona")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAdresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lozinka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdKorisnik");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("ProjekatPUSGS.Models.Letovi", b =>
                {
                    b.Property<int>("IdLet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrojILokacijePresedanja")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CenaKarte")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumIVremePoletanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DatumIVremeSletanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DuzinaPutovanja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePutovanja")
                        .HasColumnType("datetime2");

                    b.HasKey("IdLet");

                    b.ToTable("Let");
                });

            modelBuilder.Entity("ProjekatPUSGS.Models.RentacarServis", b =>
                {
                    b.Property<int>("IdServis")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenovnikUsluga")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Filijale")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PromotivniOpis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpisakVozila")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdServis");

                    b.ToTable("Servisi");
                });

            modelBuilder.Entity("ProjekatPUSGS.Models.Vozilo", b =>
                {
                    b.Property<int>("IdVozilo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrojSedista")
                        .HasColumnType("int");

                    b.Property<string>("GodinaProizvodnje")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Marka")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipVozila")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdVozilo");

                    b.ToTable("Vozila");
                });
#pragma warning restore 612, 618
        }
    }
}
